import { motion } from 'framer-motion'
import { AlertTriangle, Shield, Users, Eye, Lock, Ban, ChevronRight } from 'lucide-react'

const recommendations = [
  {
    title: 'Report Account',
    desc: 'Immediately report the cloned account to the platform using the official reporting mechanism. Include the evidence ID for faster processing.',
    priority: 'Critical',
    risk: 'Extreme',
    color: '#FF3D71',
    icon: AlertTriangle,
    action: 'Report Now',
  },
  {
    title: 'Enable Two-Factor Authentication',
    desc: 'Enable 2FA on the original account to prevent further unauthorized access attempts. Use hardware keys or authenticator apps.',
    priority: 'High',
    risk: 'High',
    color: '#FF9800',
    icon: Lock,
    action: 'Enable 2FA',
  },
  {
    title: 'Inform Followers',
    desc: 'Publish a notice on the original profile alerting followers that a cloned account exists. Include distinguishing characteristics.',
    priority: 'High',
    risk: 'High',
    color: '#FF9800',
    icon: Users,
    action: 'Draft Alert',
  },
  {
    title: 'Monitor Activity',
    desc: 'Set up automated monitoring for further clone attempts. Track mentions, tags, and impersonation patterns over the next 30 days.',
    priority: 'Medium',
    risk: 'Medium',
    color: '#FFD54F',
    icon: Eye,
    action: 'Set Monitor',
  },
  {
    title: 'Block Account',
    desc: 'Block the cloned account immediately to limit its ability to interact with your followers and associate with your brand.',
    priority: 'Medium',
    risk: 'Low',
    color: '#00FFA3',
    icon: Ban,
    action: 'Block Account',
  },
]

const priorityBadge = (priority: string) => {
  if (priority === 'Critical') return 'badge-critical'
  if (priority === 'High') return 'badge-high'
  if (priority === 'Medium') return 'badge-medium'
  return 'badge-low'
}

export default function AIRecommendation() {
  return (
    <div className="space-y-6">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
        <div className="flex items-center gap-3 mb-1">
          <div className="w-1 h-6 rounded-full" style={{ background: 'linear-gradient(180deg, #00F5FF, #7B61FF)' }} />
          <h1 className="text-2xl font-bold" style={{ fontFamily: 'Space Grotesk' }}>AI Security Recommendations</h1>
        </div>
        <p className="text-sm text-muted ml-4">Prioritized action plan generated by Recommendation Engine v2.1</p>
      </motion.div>

      {/* Banner */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="glass rounded-2xl p-5 flex items-center gap-4"
        style={{ border: '1px solid rgba(255,61,113,0.2)', background: 'rgba(255,61,113,0.04)' }}
      >
        <div className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0" style={{ background: 'rgba(255,61,113,0.1)' }}>
          <Shield size={22} color="#FF3D71" />
        </div>
        <div>
          <div className="font-bold text-sm mb-0.5" style={{ fontFamily: 'Space Grotesk', color: '#FF3D71' }}>CRITICAL THREAT DETECTED</div>
          <p className="text-xs text-muted">5 security actions recommended. Immediate response required to protect identity integrity and inform affected parties.</p>
        </div>
        <div className="ml-auto text-right hidden md:block">
          <div className="text-2xl font-bold font-mono text-danger">5</div>
          <div className="text-xs text-muted">Actions</div>
        </div>
      </motion.div>

      {/* Recommendations */}
      <div className="space-y-3">
        {recommendations.map((rec, i) => (
          <motion.div
            key={rec.title}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.1 + i * 0.1 }}
            whileHover={{ x: 4 }}
            className="glass rounded-2xl p-5"
            style={{ border: `1px solid ${rec.color}20` }}
          >
            <div className="flex items-start gap-4">
              <div
                className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0"
                style={{ background: `${rec.color}10`, border: `1px solid ${rec.color}30` }}
              >
                <rec.icon size={20} color={rec.color} />
              </div>

              <div className="flex-1">
                <div className="flex items-center gap-3 mb-2 flex-wrap">
                  <h3 className="font-bold" style={{ fontFamily: 'Space Grotesk', color: rec.color }}>{rec.title}</h3>
                  <span className={`${priorityBadge(rec.priority)} text-xs px-2 py-0.5 rounded-full font-mono`}>{rec.priority}</span>
                  <span className="text-xs text-muted font-mono">Risk: {rec.risk}</span>
                </div>
                <p className="text-sm text-muted leading-relaxed">{rec.desc}</p>
              </div>

              <motion.button
                whileHover={{ scale: 1.04 }}
                whileTap={{ scale: 0.97 }}
                className="shrink-0 px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-1.5"
                style={{
                  background: `${rec.color}15`,
                  border: `1px solid ${rec.color}40`,
                  color: rec.color,
                  fontFamily: 'Space Grotesk',
                }}
              >
                {rec.action}
                <ChevronRight size={12} />
              </motion.button>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  )
}
