import { motion } from 'framer-motion'
import { Brain } from 'lucide-react'
import { useState } from 'react'

const explanations = [
  {
    feature: 'Face Similarity',
    importance: 0.31,
    confidence: 91.3,
    weight: 'Very High',
    color: '#00F5FF',
    icon: '👤',
    detail: 'Facial embedding distance of 0.142 is well below the verification threshold of 0.40. The DeepFace model detected strong structural similarities in facial geometry including nose bridge, jaw width, and eye spacing.',
  },
  {
    feature: 'Username Similarity',
    importance: 0.24,
    confidence: 87.4,
    weight: 'High',
    color: '#7B61FF',
    icon: '@',
    detail: 'Character-level edit distance of 1 between identifiers. Pattern matches known clone techniques: digit substitution (o→0) and underscore insertion. TF-IDF semantic overlap: 94%.',
  },
  {
    feature: 'Bio Similarity',
    importance: 0.18,
    confidence: 74.2,
    weight: 'High',
    color: '#00FFA3',
    icon: '📝',
    detail: 'NLP embedding cosine similarity of 0.742 across biography text. LDA topic modelling shows 93% topic overlap. Sentiment alignment: 0.89. Near-verbatim sentence reuse detected.',
  },
  {
    feature: 'Fake Profile Model',
    importance: 0.15,
    confidence: 94.2,
    weight: 'Critical',
    color: '#FFD54F',
    icon: '🤖',
    detail: 'Gradient boosted classifier trained on 2.4M profiles. 9 engineered features triggered: recently_joined, no_external_url, follower/following ratio anomaly, username_has_numbers.',
  },
  {
    feature: 'Spammer Model',
    importance: 0.08,
    confidence: 78.4,
    weight: 'Medium',
    color: '#FF9800',
    icon: '⚠️',
    detail: '7 of 9 spam behavioural flags triggered. Account age to follower ratio is 3.4× the baseline. Posting frequency anomaly detected in first 30 days window.',
  },
  {
    feature: 'Trust Score',
    importance: 0.04,
    confidence: 12.0,
    weight: 'Low Trust',
    color: '#FF3D71',
    icon: '🛡️',
    detail: 'Composite trust score of 12/100 computed from weighted feature matrix. Profile exhibits 8 of 12 low-trust indicators. Account age: 23 days. Verification: None.',
  },
]

const summary = `The account is classified as a cloned identity with 94.2% confidence because the username similarity is extremely high (digit substitution pattern detected), biography content shows near-verbatim text reuse with 74.2% semantic overlap, the facial verification model found strong matching patterns with a cosine distance of only 0.142 (threshold: 0.40), and the behavioral analysis indicates spam characteristics with 7 of 9 risk flags triggered. The Decision Engine assigned a CRITICAL threat level based on the aggregated evidence from all five AI models.`

export default function ExplainableAI() {
  const [selected, setSelected] = useState<number | null>(null)

  return (
    <div className="space-y-6">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
        <div className="flex items-center gap-3 mb-1">
          <div className="w-1 h-6 rounded-full" style={{ background: 'linear-gradient(180deg, #00F5FF, #7B61FF)' }} />
          <h1 className="text-2xl font-bold" style={{ fontFamily: 'Space Grotesk' }}>Explainable AI</h1>
        </div>
        <p className="text-sm text-muted ml-4">Why did AI classify this profile as a Clone?</p>
      </motion.div>

      {/* AI Summary */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="glass rounded-2xl p-6"
        style={{ border: '1px solid rgba(0,245,255,0.12)' }}
      >
        <div className="flex items-start gap-4">
          <div
            className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0 animate-pulse-cyan"
            style={{ background: 'rgba(0,245,255,0.1)', border: '1px solid rgba(0,245,255,0.3)' }}
          >
            <Brain size={22} color="#00F5FF" />
          </div>
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-xs font-mono text-cyan" style={{ letterSpacing: '0.1em' }}>AI SUMMARY</span>
              <span className="text-xs text-muted">· Generated by Decision Engine v2.4</span>
            </div>
            <p className="text-sm leading-relaxed" style={{ color: '#CBD5E1', fontFamily: 'Inter' }}>{summary}</p>
          </div>
        </div>
      </motion.div>

      {/* Feature importance chart */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="glass rounded-2xl p-6"
        style={{ border: '1px solid rgba(0,245,255,0.08)' }}
      >
        <h3 className="font-bold mb-4" style={{ fontFamily: 'Space Grotesk' }}>Feature Importance</h3>
        <div className="space-y-3">
          {explanations.map((exp, i) => (
            <div key={exp.feature} className="flex items-center gap-3">
              <span className="text-sm w-36 shrink-0 text-muted">{exp.feature}</span>
              <div className="flex-1 h-5 rounded-full relative" style={{ background: 'rgba(255,255,255,0.04)' }}>
                <motion.div
                  initial={{ width: 0 }}
                  animate={{ width: `${exp.importance * 100}%` }}
                  transition={{ duration: 1, delay: 0.4 + i * 0.1 }}
                  className="h-full rounded-full"
                  style={{
                    background: `linear-gradient(90deg, ${exp.color}60, ${exp.color})`,
                    boxShadow: `0 0 8px ${exp.color}40`,
                  }}
                />
              </div>
              <span className="text-xs font-mono w-10 text-right shrink-0" style={{ color: exp.color }}>
                {(exp.importance * 100).toFixed(0)}%
              </span>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Explanation cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {explanations.map((exp, i) => (
          <motion.div
            key={exp.feature}
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 + i * 0.08 }}
            whileHover={{ y: -4, scale: 1.02 }}
            onClick={() => setSelected(selected === i ? null : i)}
            className="glass rounded-2xl p-5 cursor-pointer transition-all"
            style={{ border: `1px solid ${selected === i ? exp.color + '50' : exp.color + '18'}` }}
          >
            <div className="flex items-start justify-between mb-3">
              <div className="flex items-center gap-2">
                <span className="text-lg">{exp.icon}</span>
                <h4 className="font-semibold text-sm" style={{ fontFamily: 'Space Grotesk', color: exp.color }}>{exp.feature}</h4>
              </div>
              <span
                className="text-xs px-2 py-0.5 rounded-full font-mono"
                style={{ background: `${exp.color}15`, color: exp.color, border: `1px solid ${exp.color}30` }}
              >
                {exp.weight}
              </span>
            </div>

            <div className="space-y-2 mb-3">
              {[
                { label: 'Importance', value: `${(exp.importance * 100).toFixed(0)}%` },
                { label: 'Confidence', value: `${exp.confidence}%` },
              ].map((m) => (
                <div key={m.label} className="flex justify-between text-xs">
                  <span className="text-muted">{m.label}</span>
                  <span className="font-mono" style={{ color: exp.color }}>{m.value}</span>
                </div>
              ))}
            </div>

            <div className="h-1 rounded-full mb-3" style={{ background: 'rgba(255,255,255,0.06)' }}>
              <div className="h-full rounded-full" style={{ width: `${exp.confidence}%`, background: exp.color, boxShadow: `0 0 6px ${exp.color}` }} />
            </div>

            {selected === i && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                exit={{ opacity: 0, height: 0 }}
                className="text-xs leading-relaxed pt-3 border-t"
                style={{ borderColor: `${exp.color}20`, color: '#94A3B8' }}
              >
                {exp.detail}
              </motion.div>
            )}

            {selected !== i && (
              <p className="text-xs text-muted leading-relaxed line-clamp-2">{exp.detail}</p>
            )}
          </motion.div>
        ))}
      </div>
    </div>
  )
}
